version: "3"

services:
    home-assistant:
        image: ghcr.io/home-assistant/home-assistant:stable
        container_name: homeassistant
        network_mode: host
        privileged: true
        volumes:
            - ./home-assistant/config:/config
        environment:
            - TZ=Europe/Berlin
        restart: unless-stopped
    mosquitto:
        image: eclipse-mosquitto:latest
        container_name: mosquitto
        ports:
            - 1883:1883
        volumes:
            - ./mosquitto/config:/mosquitto/config
        restart: unless-stopped
