esphome:
  name: "ambient_light"
  friendly_name: "ambient_light"

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

mqtt:
  broker: 192.168.178.134

switch:
  - platform: gpio
    name: "esp32 led"
    pin: 2

sensor:
  - platform: bh1750
    name: "BH1750 Illuminance Sensor"
    address: 0x23
    update_interval: 10s

# Defines which GPIO pins have to be connected to sda, scl
i2c:
  sda: 21
  scl: 22
  scan: true
  id: bus_a
  
ota:
  password: "f9a4220a68b3b77a436e6e2aa3bd2768"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Jkjkj Fallback Hotspot"
    password: "31g2zjHsys5v"

captive_portal:
    