esphome:
  name: esp2
  friendly_name: esp2

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "mSqhJP9Ps4mYlZLmBntf0gGBsUBGcbxOpLzwhJ1C+4A="

ota:
  password: "838ac453db59b2e7a34d6d58c3276f87"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp2 Fallback Hotspot"
    password: "nTs8yWriEip5"

captive_portal:
    
light:
  - platform: fastled_clockless
    chipset: WS2812B
    pin: GPIO16
    num_leds: 3
    name: "FastLED WS2812B Light"
